# Generated by Django 4.2.1 on 2023-07-26 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category_shopping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopping_category_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Shopping_Category',
                'verbose_name_plural': 'Shopping_Categories',
            },
        ),
        migrations.CreateModel(
            name='Store_shopping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopping_store', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Shopping_store',
                'verbose_name_plural': 'Shopping_stores',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=1)),
                ('category_shopping', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.category_shopping')),
                ('store_shopping', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.store_shopping')),
            ],
        ),
    ]
