# Generated by Django 4.2.1 on 2023-05-12 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0002_delete_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pendiente', models.CharField(choices=[('General', 'General'), ('Cortar-Pasto', 'Cortar-Pasto'), ('Limpiar-Casa-Salon', 'Limpiar-Casa-Salon'), ('Limpiar-Perrera', 'Limpiar-Perrera'), ('Desyerbar-Huerta', 'Desyerbar-Huerta'), ('Platear-Arboles', 'Platear-Arboles'), ('Veneno-Ratas', 'Veneno-Ratas')], max_length=20)),
                ('tcompletado', models.BooleanField(default=False)),
                ('fecha_terminado', models.DateField(auto_now_add=True)),
                ('responsable', models.ForeignKey(default='TBA', on_delete=django.db.models.deletion.CASCADE, related_name='asignee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
