# Generated by Django 4.2.1 on 2023-06-21 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'TaskName',
                'verbose_name_plural': 'Tasks',
            },
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['tcompletado']},
        ),
        migrations.RemoveField(
            model_name='task',
            name='pendiente',
        ),
        migrations.AddField(
            model_name='task',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='responsable',
            field=models.ForeignKey(blank=True, default='TBA', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.task_name'),
        ),
    ]
