# Generated by Django 4.2.1 on 2023-06-21 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_name_alter_task_options_remove_task_pendiente_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task_name',
            options={'verbose_name': 'TaskName', 'verbose_name_plural': 'TaskNames'},
        ),
    ]
